package IntefazConUsuario;

import javax.swing.*;
import java.awt.*;

public class GUI extends JFrame {
	private JTabbedPane trianguloTabbedPane;
	private JPanel ventana;
	private JTabbedPane rectanguloTabbedPane;
	private JTabbedPane romboideTabbedPane;
	private JScrollPane trianguloJScrollPane;
	private JScrollPane rectanguloJScrollPane;
	private JScrollPane romboideJScrollPane;
	private JTextArea calculaElAreaYTextArea;

	public static void main(String[] args) {
		JFrame frame = new JFrame("GUI");
		frame.setContentPane(new GUI().ventana);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		ventana = new JPanel();
		ventana.setLayout(new GridBagLayout());
		ventana.setName("ventana");
		trianguloTabbedPane = new JTabbedPane();
		trianguloTabbedPane.setName("Triangulo");
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.BOTH;
		ventana.add(trianguloTabbedPane, gbc);
		trianguloJScrollPane = new JScrollPane();
		trianguloTabbedPane.addTab("Triangulo", trianguloJScrollPane);
		calculaElAreaYTextArea = new JTextArea();
		calculaElAreaYTextArea.setEditable(false);
		calculaElAreaYTextArea.setEnabled(true);
		calculaElAreaYTextArea.setText("Calcula el area y perimetro de un triangulo.\nIngresando base, altura, y los 2 lados que no son la base.");
		trianguloJScrollPane.setViewportView(calculaElAreaYTextArea);
		rectanguloTabbedPane = new JTabbedPane();
		rectanguloTabbedPane.setName("Rectangulo");
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.BOTH;
		ventana.add(rectanguloTabbedPane, gbc);
		rectanguloJScrollPane = new JScrollPane();
		rectanguloTabbedPane.addTab("Rectangulo", rectanguloJScrollPane);
		romboideTabbedPane = new JTabbedPane();
		romboideTabbedPane.setName("Romboide");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.BOTH;
		ventana.add(romboideTabbedPane, gbc);
		romboideJScrollPane = new JScrollPane();
		romboideTabbedPane.addTab("Romboide", romboideJScrollPane);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return ventana;
	}

}
