package IntefazConUsuario;

import javax.swing.*;
import java.awt.*;

public class Inicio extends JFrame {
	private JTabbedPane figurasTabbedPane;
	private JPanel ventana;
	private JPanel trianguloJPanel;
	private JPanel rectanguloJPanel;
	private JPanel romboideJPanel;

	public static void main(String[] args) {
		JFrame frame = new JFrame("Figuras Geometricas");
		frame.setContentPane(new Inicio().ventana);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.pack();
		frame.setVisible(true);
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		ventana = new JPanel();
		ventana.setLayout(new GridBagLayout());
		ventana.setName("");
		figurasTabbedPane = new JTabbedPane();
		figurasTabbedPane.setName("Figuras");
		figurasTabbedPane.setTabLayoutPolicy(0);
		figurasTabbedPane.setTabPlacement(2);
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.BOTH;
		ventana.add(figurasTabbedPane, gbc);
		trianguloJPanel = new JPanel();
		trianguloJPanel.setLayout(new GridBagLayout());
		trianguloJPanel.setName("");
		figurasTabbedPane.addTab("", trianguloJPanel);
		romboideJPanel = new JPanel();
		romboideJPanel.setLayout(new GridBagLayout());
		romboideJPanel.setName("");
		figurasTabbedPane.addTab("", romboideJPanel);
		rectanguloJPanel = new JPanel();
		rectanguloJPanel.setLayout(new GridBagLayout());
		rectanguloJPanel.setName("");
		figurasTabbedPane.addTab("", rectanguloJPanel);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return ventana;
	}

}
