package IntefazConUsuario;

import Operacion.Triangulo;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class PestañaTriangulo extends Inicio {

	private JPanel trianguloJPanel;
	private JPanel descripcionJPanel;
	private JPanel resultadosJPanel;
	private JTextField descripcionTextField;
	private JTextField ladoATextField;
	private JTextField ladoBTextField;
	private JTextField baseTextField;
	private JTextField alturaTextField;
	private JButton calcularButton;
	private JLabel ladoAJLabel;
	private JLabel ladoBJLabel;
	private JLabel baseJLabel;
	private JLabel alturaJLabel;
	private JLabel perimetroJLabel;
	private JLabel areaJLabel;

	public PestañaTriangulo() {
		descripcionTextField.setText("Aquí podras calcular el area y perimetro de un triángulo.\nProporcionando la base y la altura.\nPara mostrar los resultados presionar el boton \"Calcular\"");
		baseJLabel.setText("Base:");
		baseJLabel.setLabelFor(baseTextField);
		baseTextField.setText("Base");
		baseTextField.setToolTipText("Ingrese la base del triángulo: ");
		alturaJLabel.setText("Altura: ");
		alturaJLabel.setLabelFor(alturaTextField);
		alturaTextField.setText("Altura");
		alturaTextField.setToolTipText("Ingrese la altura del triángulo: ");
		calcularButton.setText("Calcular");

		baseTextField.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (baseTextField.getText().equals("Base"))
					baseTextField.setText("");
			}
		});
		alturaTextField.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (alturaTextField.getText().equals("Altura"))
					baseTextField.setText("");
			}
		});
		calcularButton.addActionListener(actionEvent -> {
			Triangulo triangulo = new Triangulo();
			triangulo.setAltura(Float.parseFloat(alturaTextField.getText()));
			triangulo.setBase(Float.parseFloat(baseTextField.getText()));
			double area;
			float perimetro;
			perimetro = triangulo.calcularPerimetro();
			perimetroJLabel.setText("El perimetro del triángulo es: "+perimetro);
			area = triangulo.calcularArea();
			areaJLabel.setText("El area del triángulo es: "+area);
		});
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridBagLayout());
	}
}
