package IntefazConUsuario;

import Operacion.Rectangulo;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class PestañaRectangulo extends JPanel {
	private JPanel rectanguloJPanel;
	private JTextField instruccionesTextField;
	private JTextField baseTextField;
	private JTextField alturaTextField;
	private JLabel baseJLabel;
	private JLabel alturaJLabel;
	private JButton calcularButton;
	private JPanel descripcionJPanel;
	private JPanel resultadosJPanel;
	private JLabel perimetroJLabel;
	private JLabel areaJLabel;

	public PestañaRectangulo() {
		instruccionesTextField.setText("Aquí podras calcular el area y perimetro de un rectangulo.\nProporcionando la base y la altura.\nPara mostrar los resultados presionar el boton \"Calcular\"");
		baseJLabel.setText("Base:");
		baseJLabel.setLabelFor(baseTextField);
		baseTextField.setText("Base");
		baseTextField.setToolTipText("Ingrese la base del rectángulo: ");
		alturaJLabel.setText("Altura: ");
		alturaJLabel.setLabelFor(alturaTextField);
		alturaTextField.setText("Altura");
		alturaTextField.setToolTipText("Ingrese la altura del rectángulo: ");
		calcularButton.setText("Calcular");

		baseTextField.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (baseTextField.getText().equals("Base"))
					baseTextField.setText("");
			}
		});
		alturaTextField.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (alturaTextField.getText().equals("Altura"))
					baseTextField.setText("");
			}
		});
		calcularButton.addActionListener(actionEvent -> {
			Rectangulo rectangulo = new Rectangulo();
			rectangulo.setAltura(Float.parseFloat(alturaTextField.getText()));
			rectangulo.setBase(Float.parseFloat(baseTextField.getText()));
			double area;
			float perimetro;
			perimetro = rectangulo.calcularPerimetro();
			perimetroJLabel.setText("El perimetro del rectangulo es: " + perimetro);
			area = rectangulo.calcularArea();
			areaJLabel.setText("El area del rectangulo es: " + area);
		});
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		rectanguloJPanel = new JPanel();
		rectanguloJPanel.setLayout(new GridBagLayout());
		descripcionJPanel = new JPanel();
		descripcionJPanel.setLayout(new GridBagLayout());
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.gridwidth = 3;
		gbc.gridheight = 5;
		gbc.fill = GridBagConstraints.BOTH;
		rectanguloJPanel.add(descripcionJPanel, gbc);
		instruccionesTextField = new JTextField();
		instruccionesTextField.setEditable(false);
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.gridwidth = 3;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		descripcionJPanel.add(instruccionesTextField, gbc);
		baseJLabel = new JLabel();
		baseJLabel.setText("");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		descripcionJPanel.add(baseJLabel, gbc);
		alturaJLabel = new JLabel();
		alturaJLabel.setText("");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		descripcionJPanel.add(alturaJLabel, gbc);
		final JPanel spacer1 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		descripcionJPanel.add(spacer1, gbc);
		baseTextField = new JTextField();
		baseTextField.setToolTipText("");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		descripcionJPanel.add(baseTextField, gbc);
		alturaTextField = new JTextField();
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		descripcionJPanel.add(alturaTextField, gbc);
		calcularButton = new JButton();
		calcularButton.setText("");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 4;
		gbc.gridwidth = 3;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		descripcionJPanel.add(calcularButton, gbc);
		final JPanel spacer2 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.gridwidth = 3;
		gbc.fill = GridBagConstraints.VERTICAL;
		descripcionJPanel.add(spacer2, gbc);
		resultadosJPanel = new JPanel();
		resultadosJPanel.setLayout(new GridBagLayout());
		resultadosJPanel.setVisible(true);
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 5;
		gbc.gridwidth = 3;
		gbc.fill = GridBagConstraints.BOTH;
		rectanguloJPanel.add(resultadosJPanel, gbc);
		perimetroJLabel = new JLabel();
		perimetroJLabel.setText("");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		resultadosJPanel.add(perimetroJLabel, gbc);
		final JPanel spacer3 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.fill = GridBagConstraints.VERTICAL;
		resultadosJPanel.add(spacer3, gbc);
		areaJLabel = new JLabel();
		areaJLabel.setText("");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		resultadosJPanel.add(areaJLabel, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return rectanguloJPanel;
	}

}
