package IntefazConUsuario;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class Rectangulo extends Inicio {
	private JPanel recatanguloJPanel;
	private JTextField instruccionesTextField;
	private JTextField baseTextField;
	private JTextField alturaTextField;
	private JLabel baseJLabel;
	private JLabel alturaJLabel;
	private JButton calcularButton;
	private JPanel descripcionJPanel;
	private JPanel resultadosJPanel;
	private JLabel perimetroJLabel;
	private JLabel areaJLabel;

	public Rectangulo() {
		instruccionesTextField.setText("Aquí podras calcular el area y perimetro de un rectangulo." +
				"\nProporcionando la base y la altura.");
		baseJLabel.setText("Base:");
		baseJLabel.setLabelFor(baseTextField);
		baseTextField.setText("Base");
		baseTextField.setToolTipText("Ingrese la base del rectángulo: ");
		alturaJLabel.setText("Altura: ");
		alturaJLabel.setLabelFor(alturaTextField);
		alturaTextField.setText("Altura");
		alturaTextField.setToolTipText("Ingrese la altura del rectángulo: ");
		calcularButton.setText("Calcular");

		baseTextField.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (baseTextField.getText().equals("Base"))
					baseTextField.setText("");
			}
		});
		alturaTextField.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				if (alturaTextField.getText().equals("Altura"))
					baseTextField.setText("");
			}
		});
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		recatanguloJPanel = new JPanel();
		recatanguloJPanel.setLayout(new GridBagLayout());
		descripcionJPanel = new JPanel();
		descripcionJPanel.setLayout(new GridBagLayout());
		GridBagConstraints gbc;
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.gridwidth = 3;
		gbc.gridheight = 5;
		gbc.fill = GridBagConstraints.BOTH;
		recatanguloJPanel.add(descripcionJPanel, gbc);
		instruccionesTextField = new JTextField();
		instruccionesTextField.setEditable(false);
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.gridwidth = 3;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		descripcionJPanel.add(instruccionesTextField, gbc);
		baseJLabel = new JLabel();
		baseJLabel.setText("");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		descripcionJPanel.add(baseJLabel, gbc);
		alturaJLabel = new JLabel();
		alturaJLabel.setText("");
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 1;
		gbc.anchor = GridBagConstraints.WEST;
		descripcionJPanel.add(alturaJLabel, gbc);
		final JPanel spacer1 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 1;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		descripcionJPanel.add(spacer1, gbc);
		baseTextField = new JTextField();
		baseTextField.setToolTipText("");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		descripcionJPanel.add(baseTextField, gbc);
		alturaTextField = new JTextField();
		gbc = new GridBagConstraints();
		gbc.gridx = 2;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		descripcionJPanel.add(alturaTextField, gbc);
		calcularButton = new JButton();
		calcularButton.setText("");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 4;
		gbc.gridwidth = 3;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		descripcionJPanel.add(calcularButton, gbc);
		final JPanel spacer2 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 3;
		gbc.gridwidth = 3;
		gbc.fill = GridBagConstraints.VERTICAL;
		descripcionJPanel.add(spacer2, gbc);
		resultadosJPanel = new JPanel();
		resultadosJPanel.setLayout(new GridBagLayout());
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 5;
		gbc.gridwidth = 3;
		gbc.fill = GridBagConstraints.BOTH;
		recatanguloJPanel.add(resultadosJPanel, gbc);
		perimetroJLabel = new JLabel();
		perimetroJLabel.setText("");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 0;
		gbc.anchor = GridBagConstraints.WEST;
		resultadosJPanel.add(perimetroJLabel, gbc);
		final JPanel spacer3 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 1;
		gbc.gridy = 0;
		gbc.fill = GridBagConstraints.HORIZONTAL;
		resultadosJPanel.add(spacer3, gbc);
		final JPanel spacer4 = new JPanel();
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 1;
		gbc.fill = GridBagConstraints.VERTICAL;
		resultadosJPanel.add(spacer4, gbc);
		areaJLabel = new JLabel();
		areaJLabel.setText("");
		gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.gridy = 2;
		gbc.anchor = GridBagConstraints.WEST;
		resultadosJPanel.add(areaJLabel, gbc);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return recatanguloJPanel;
	}
}
